# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      timezone: 'Europe/Berlin'
      interval: 'monthly'
    assignees:
      - 'DJBlackEagle'
    commit-message:
      prefix: 'chore(github)'
    open-pull-requests-limit: 10
    labels:
      - 'dependabot'
      - 'github-actions'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      timezone: 'Europe/Berlin'
      interval: 'monthly'
    assignees:
      - 'DJBlackEagle'
    commit-message:
      prefix: 'chore(deps)'
    open-pull-requests-limit: 10
    labels:
      - 'dependabot'
      - 'dependencies'
    versioning-strategy: increase
